language: ruby
cache: bundler
bundler_args: "--binstubs --without documentation --path ../bundle --retry=3 --jobs=3"
rvm:
- 1.9.3
- 2.0.0
- ruby-head

script: bundle exec rspec spec --require spec_helper

addons:
  code_climate:
    repo_token: 1d59bfbc2b71cac7d09292de4e62b41e77693c5f46e43dd3ca62c7579c9d0caa
